{
    "openapi": "3.0.1",
    "info": {
        "title": "中间层模块",
        "description": "虚拟宠物医院API文档，前端用",
        "version": "0.0.1-SNAPSHOT"
    },
    "servers": [
        {
            "url": "http://localhost:8090",
            "description": "Generated server url"
        }
    ],
    "paths": {
        "/api/file/image": {
            "put": {
                "tags": [
                    "数据传输模块"
                ],
                "summary": "图片格式转换接口",
                "operationId": "convertImage",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "json",
                                "description": "图片格式转换信息",
                                "example": {
                                    "filePath": "/Users/xxx/Documents/Java/intermediatorServiceData/data/test/fe0151e3-188a-4342-8042-33d476394aa0/WallPaper_KirbyDiscovery_1920_1080.jpg",
                                    "expectedFormat": "png"
                                }
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "example": {
                                    "code": 200,
                                    "message": "ok",
                                    "filePath": "/Users/xxx/Documents/Java/intermediatorServiceData/data/test/fe0151e3-188a-4342-8042-33d476394aa0/WallPaper_KirbyDiscovery_1920_1080.png"
                                }
                            }
                        }
                    },
                    "515": {
                        "description": "Request failed",
                        "content": {
                            "application/json": {
                                "example": {
                                    "code": 515,
                                    "message": "Request failed"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/auth/user": {
            "get": {
                "tags": [
                    "鉴权模块"
                ],
                "summary": "获取用户列表接口",
                "operationId": "getUsers",
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "example": {
                                    "code": 200,
                                    "data": {
                                        "userList": [
                                            {
                                                "userPassword": "test",
                                                "userAuthority": 3,
                                                "userName": "test@test.com",
                                                "userId": 2
                                            },
                                            {
                                                "userPassword": "tttt",
                                                "userAuthority": 3,
                                                "userName": "tt",
                                                "userId": 6
                                            }
                                        ]
                                    }
                                }
                            }
                        }
                    },
                    "515": {
                        "description": "Request failed",
                        "content": {
                            "application/json": {
                                "example": {
                                    "code": 515,
                                    "message": "Request failed"
                                }
                            }
                        }
                    }
                }
            },
            "put": {
                "tags": [
                    "鉴权模块"
                ],
                "summary": "更改用户信息接口",
                "operationId": "updateUser",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "json",
                                "description": "更改后的用户信息",
                                "example": {
                                    "userId": 2,
                                    "userName": "test@test.com",
                                    "userPassword": "tttt",
                                    "userAuthority": 3
                                }
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "515": {
                        "description": "Request failed",
                        "content": {
                            "application/json": {
                                "example": {
                                    "code": 515,
                                    "message": "Request failed"
                                }
                            }
                        }
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "example": {
                                    "code": 200,
                                    "message": "ok",
                                    "data": {
                                        "userPassword": "admin",
                                        "userName": "admin@admin.com",
                                        "userAuthority": 1,
                                        "userId": 1
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "鉴权模块"
                ],
                "summary": "新增用户接口",
                "operationId": "addUser",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "json",
                                "description": "新增的用户信息",
                                "example": {
                                    "userName": "test@test.com",
                                    "userPassword": "tttt",
                                    "userAuthority": 3
                                }
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "515": {
                        "description": "Request failed",
                        "content": {
                            "application/json": {
                                "example": {
                                    "code": 515,
                                    "message": "Request failed"
                                }
                            }
                        }
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "example": {
                                    "code": 200,
                                    "message": "ok",
                                    "data": {
                                        "userPassword": "admin",
                                        "userName": "admin@admin.com",
                                        "userAuthority": 1,
                                        "userId": 1
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/file/files": {
            "get": {
                "tags": [
                    "数据传输模块"
                ],
                "summary": "下载文件接口",
                "operationId": "downloadFile",
                "parameters": [
                    {
                        "name": "filePath",
                        "in": "query",
                        "description": "文件存储路径",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "multipart/form-data": {
                                "schema": {
                                    "type": "string",
                                    "format": "binary"
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "数据传输模块"
                ],
                "summary": "上传文件接口",
                "operationId": "uploadFile",
                "parameters": [
                    {
                        "name": "filePath",
                        "in": "query",
                        "description": "文件存储路径",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "required": [
                                    "file"
                                ],
                                "type": "object",
                                "properties": {
                                    "file": {
                                        "type": "string",
                                        "description": "文件",
                                        "format": "binary"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "example": {
                                    "code": 200,
                                    "message": "ok"
                                }
                            }
                        }
                    },
                    "430": {
                        "description": "File transfer failed",
                        "content": {
                            "application/json": {
                                "example": {
                                    "code": 430,
                                    "message": "File transfer error"
                                }
                            }
                        }
                    },
                    "431": {
                        "description": "File empty",
                        "content": {
                            "application/json": {
                                "example": {
                                    "code": 431,
                                    "message": "File empty error"
                                }
                            }
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "数据传输模块"
                ],
                "summary": "删除文件接口",
                "operationId": "deleteFile",
                "parameters": [
                    {
                        "name": "filePath",
                        "in": "query",
                        "description": "文件存储路径",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "example": {
                                    "code": 200,
                                    "message": "ok",
                                    "filePath": "/Users/xxx/Documents/Java/intermediatorServiceData/data/test/fe0151e3-188a-4342-8042-33d476394aa0/WallPaper_KirbyDiscovery_1920_1080.png"
                                }
                            }
                        }
                    },
                    "515": {
                        "description": "Request failed",
                        "content": {
                            "application/json": {
                                "example": {
                                    "code": 515,
                                    "message": "Request failed"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/auth/login": {
            "post": {
                "tags": [
                    "鉴权模块"
                ],
                "summary": "系统登录接口",
                "operationId": "login",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "json",
                                "description": "登录用户信息",
                                "example": {
                                    "userName": "test@test.com",
                                    "userPassword": "tttt"
                                }
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "application/json": {
                                "example": {
                                    "code": 401,
                                    "message": "Unauthorized"
                                }
                            }
                        }
                    },
                    "515": {
                        "description": "Request failed",
                        "content": {
                            "application/json": {
                                "example": {
                                    "code": 515,
                                    "message": "Request failed"
                                }
                            }
                        }
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "example": {
                                    "code": 200,
                                    "message": "ok",
                                    "data": {
                                        "userPassword": "admin",
                                        "userName": "admin@admin.com",
                                        "userAuthority": 1,
                                        "userId": 1
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/auth/user/{userNameKeyword}": {
            "get": {
                "tags": [
                    "鉴权模块"
                ],
                "summary": "获取用户列表接口",
                "operationId": "getUsersByKeyword",
                "parameters": [
                    {
                        "name": "userNameKeyword",
                        "in": "path",
                        "description": "用户名关键字，支持模糊查询",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "example": {
                                    "code": 200,
                                    "data": {
                                        "userList": [
                                            {
                                                "userPassword": "test",
                                                "userAuthority": 3,
                                                "userName": "test@test.com",
                                                "userId": 2
                                            },
                                            {
                                                "userPassword": "tttt",
                                                "userAuthority": 3,
                                                "userName": "tt",
                                                "userId": 6
                                            }
                                        ]
                                    }
                                }
                            }
                        }
                    },
                    "515": {
                        "description": "Request failed",
                        "content": {
                            "application/json": {
                                "example": {
                                    "code": 515,
                                    "message": "Request failed"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/auth/user/{userId}": {
            "delete": {
                "tags": [
                    "鉴权模块"
                ],
                "summary": "删除用户接口",
                "operationId": "deleteUser",
                "parameters": [
                    {
                        "name": "userId",
                        "in": "path",
                        "description": "用户Id",
                        "required": true,
                        "schema": {
                            "type": "integer",
                            "format": "int32"
                        }
                    }
                ],
                "responses": {
                    "515": {
                        "description": "Request failed",
                        "content": {
                            "application/json": {
                                "example": {
                                    "code": 515,
                                    "message": "Request failed"
                                }
                            }
                        }
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "example": {
                                    "code": 200,
                                    "message": "ok",
                                    "data": {
                                        "userPassword": "admin",
                                        "userName": "admin@admin.com",
                                        "userAuthority": 1,
                                        "userId": 1
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "components": {}
}